/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminIndexRouteImport } from './routes/_admin/index'
import { Route as AdminNotificationRouteImport } from './routes/_admin/notification'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminUserIndexRouteImport } from './routes/_admin/user/index'
import { Route as AdminTicketIndexRouteImport } from './routes/_admin/ticket/index'
import { Route as AdminCourseIndexRouteImport } from './routes/_admin/course/index'
import { Route as AdminBlogIndexRouteImport } from './routes/_admin/blog/index'
import { Route as AdminTicketCategoryRouteImport } from './routes/_admin/ticket/category'
import { Route as AdminTicketTicketIdRouteImport } from './routes/_admin/ticket/$ticketId'
import { Route as AdminCourseCreateRouteImport } from './routes/_admin/course/create'
import { Route as AdminCourseCategoryRouteImport } from './routes/_admin/course/category'
import { Route as AdminCourseCourseIdRouteImport } from './routes/_admin/course/$courseId'
import { Route as AdminBlogCreateRouteImport } from './routes/_admin/blog/create'
import { Route as AdminBlogCategoryRouteImport } from './routes/_admin/blog/category'
import { Route as AdminBlogBlogIdRouteImport } from './routes/_admin/blog/$blogId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationRoute = AdminNotificationRouteImport.update({
  id: '/notification',
  path: '/notification',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUserIndexRoute = AdminUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketIndexRoute = AdminTicketIndexRouteImport.update({
  id: '/ticket/',
  path: '/ticket/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCourseIndexRoute = AdminCourseIndexRouteImport.update({
  id: '/course/',
  path: '/course/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketCategoryRoute = AdminTicketCategoryRouteImport.update({
  id: '/ticket/category',
  path: '/ticket/category',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketTicketIdRoute = AdminTicketTicketIdRouteImport.update({
  id: '/ticket/$ticketId',
  path: '/ticket/$ticketId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCourseCreateRoute = AdminCourseCreateRouteImport.update({
  id: '/course/create',
  path: '/course/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCourseCategoryRoute = AdminCourseCategoryRouteImport.update({
  id: '/course/category',
  path: '/course/category',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCourseCourseIdRoute = AdminCourseCourseIdRouteImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogCreateRoute = AdminBlogCreateRouteImport.update({
  id: '/blog/create',
  path: '/blog/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogCategoryRoute = AdminBlogCategoryRouteImport.update({
  id: '/blog/category',
  path: '/blog/category',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogBlogIdRoute = AdminBlogBlogIdRouteImport.update({
  id: '/blog/$blogId',
  path: '/blog/$blogId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AdminDashboardRoute
  '/notification': typeof AdminNotificationRoute
  '/blog/$blogId': typeof AdminBlogBlogIdRoute
  '/blog/category': typeof AdminBlogCategoryRoute
  '/blog/create': typeof AdminBlogCreateRoute
  '/course/$courseId': typeof AdminCourseCourseIdRoute
  '/course/category': typeof AdminCourseCategoryRoute
  '/course/create': typeof AdminCourseCreateRoute
  '/ticket/$ticketId': typeof AdminTicketTicketIdRoute
  '/ticket/category': typeof AdminTicketCategoryRoute
  '/blog/': typeof AdminBlogIndexRoute
  '/course/': typeof AdminCourseIndexRoute
  '/ticket/': typeof AdminTicketIndexRoute
  '/user/': typeof AdminUserIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/dashboard': typeof AdminDashboardRoute
  '/notification': typeof AdminNotificationRoute
  '/': typeof AdminIndexRoute
  '/blog/$blogId': typeof AdminBlogBlogIdRoute
  '/blog/category': typeof AdminBlogCategoryRoute
  '/blog/create': typeof AdminBlogCreateRoute
  '/course/$courseId': typeof AdminCourseCourseIdRoute
  '/course/category': typeof AdminCourseCategoryRoute
  '/course/create': typeof AdminCourseCreateRoute
  '/ticket/$ticketId': typeof AdminTicketTicketIdRoute
  '/ticket/category': typeof AdminTicketCategoryRoute
  '/blog': typeof AdminBlogIndexRoute
  '/course': typeof AdminCourseIndexRoute
  '/ticket': typeof AdminTicketIndexRoute
  '/user': typeof AdminUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/notification': typeof AdminNotificationRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/blog/$blogId': typeof AdminBlogBlogIdRoute
  '/_admin/blog/category': typeof AdminBlogCategoryRoute
  '/_admin/blog/create': typeof AdminBlogCreateRoute
  '/_admin/course/$courseId': typeof AdminCourseCourseIdRoute
  '/_admin/course/category': typeof AdminCourseCategoryRoute
  '/_admin/course/create': typeof AdminCourseCreateRoute
  '/_admin/ticket/$ticketId': typeof AdminTicketTicketIdRoute
  '/_admin/ticket/category': typeof AdminTicketCategoryRoute
  '/_admin/blog/': typeof AdminBlogIndexRoute
  '/_admin/course/': typeof AdminCourseIndexRoute
  '/_admin/ticket/': typeof AdminTicketIndexRoute
  '/_admin/user/': typeof AdminUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/notification'
    | '/blog/$blogId'
    | '/blog/category'
    | '/blog/create'
    | '/course/$courseId'
    | '/course/category'
    | '/course/create'
    | '/ticket/$ticketId'
    | '/ticket/category'
    | '/blog/'
    | '/course/'
    | '/ticket/'
    | '/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/dashboard'
    | '/notification'
    | '/'
    | '/blog/$blogId'
    | '/blog/category'
    | '/blog/create'
    | '/course/$courseId'
    | '/course/category'
    | '/course/create'
    | '/ticket/$ticketId'
    | '/ticket/category'
    | '/blog'
    | '/course'
    | '/ticket'
    | '/user'
  id:
    | '__root__'
    | '/_admin'
    | '/login'
    | '/_admin/dashboard'
    | '/_admin/notification'
    | '/_admin/'
    | '/_admin/blog/$blogId'
    | '/_admin/blog/category'
    | '/_admin/blog/create'
    | '/_admin/course/$courseId'
    | '/_admin/course/category'
    | '/_admin/course/create'
    | '/_admin/ticket/$ticketId'
    | '/_admin/ticket/category'
    | '/_admin/blog/'
    | '/_admin/course/'
    | '/_admin/ticket/'
    | '/_admin/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/notification': {
      id: '/_admin/notification'
      path: '/notification'
      fullPath: '/notification'
      preLoaderRoute: typeof AdminNotificationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/user/': {
      id: '/_admin/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof AdminUserIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/ticket/': {
      id: '/_admin/ticket/'
      path: '/ticket'
      fullPath: '/ticket/'
      preLoaderRoute: typeof AdminTicketIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/course/': {
      id: '/_admin/course/'
      path: '/course'
      fullPath: '/course/'
      preLoaderRoute: typeof AdminCourseIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/blog/': {
      id: '/_admin/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/ticket/category': {
      id: '/_admin/ticket/category'
      path: '/ticket/category'
      fullPath: '/ticket/category'
      preLoaderRoute: typeof AdminTicketCategoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/ticket/$ticketId': {
      id: '/_admin/ticket/$ticketId'
      path: '/ticket/$ticketId'
      fullPath: '/ticket/$ticketId'
      preLoaderRoute: typeof AdminTicketTicketIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/course/create': {
      id: '/_admin/course/create'
      path: '/course/create'
      fullPath: '/course/create'
      preLoaderRoute: typeof AdminCourseCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/course/category': {
      id: '/_admin/course/category'
      path: '/course/category'
      fullPath: '/course/category'
      preLoaderRoute: typeof AdminCourseCategoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/course/$courseId': {
      id: '/_admin/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof AdminCourseCourseIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/blog/create': {
      id: '/_admin/blog/create'
      path: '/blog/create'
      fullPath: '/blog/create'
      preLoaderRoute: typeof AdminBlogCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/blog/category': {
      id: '/_admin/blog/category'
      path: '/blog/category'
      fullPath: '/blog/category'
      preLoaderRoute: typeof AdminBlogCategoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/blog/$blogId': {
      id: '/_admin/blog/$blogId'
      path: '/blog/$blogId'
      fullPath: '/blog/$blogId'
      preLoaderRoute: typeof AdminBlogBlogIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminNotificationRoute: typeof AdminNotificationRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogBlogIdRoute: typeof AdminBlogBlogIdRoute
  AdminBlogCategoryRoute: typeof AdminBlogCategoryRoute
  AdminBlogCreateRoute: typeof AdminBlogCreateRoute
  AdminCourseCourseIdRoute: typeof AdminCourseCourseIdRoute
  AdminCourseCategoryRoute: typeof AdminCourseCategoryRoute
  AdminCourseCreateRoute: typeof AdminCourseCreateRoute
  AdminTicketTicketIdRoute: typeof AdminTicketTicketIdRoute
  AdminTicketCategoryRoute: typeof AdminTicketCategoryRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminCourseIndexRoute: typeof AdminCourseIndexRoute
  AdminTicketIndexRoute: typeof AdminTicketIndexRoute
  AdminUserIndexRoute: typeof AdminUserIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminNotificationRoute: AdminNotificationRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogBlogIdRoute: AdminBlogBlogIdRoute,
  AdminBlogCategoryRoute: AdminBlogCategoryRoute,
  AdminBlogCreateRoute: AdminBlogCreateRoute,
  AdminCourseCourseIdRoute: AdminCourseCourseIdRoute,
  AdminCourseCategoryRoute: AdminCourseCategoryRoute,
  AdminCourseCreateRoute: AdminCourseCreateRoute,
  AdminTicketTicketIdRoute: AdminTicketTicketIdRoute,
  AdminTicketCategoryRoute: AdminTicketCategoryRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminCourseIndexRoute: AdminCourseIndexRoute,
  AdminTicketIndexRoute: AdminTicketIndexRoute,
  AdminUserIndexRoute: AdminUserIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
